//
// Created by Kevin Tan on 2021/11/18.
//

#ifndef CODE_OPCODE_H
#define CODE_OPCODE_H

enum OpCode {
    LOAD_OBJECT,
    STORE_OBJECT,
    BUILD_ARRAY,
    INIT_ARRAY,
    SUBSCR_ARRAY,
    STORE_SUBSCR,

    CALL_PRINTF,
    CALL_GETINT,
    EXIT_INTERP,
    // JUMP_ABSOLUTE,
    // JUMP_FORWARD,
    JUMP_IF_FALSE_OR_POP,
    JUMP_IF_TRUE_OR_POP,
    CALL_FUNCTION,
    RETURN_VALUE,

    UNARY_OP,
    BINARY_OP,

    POP_TOP,
    NOP
};

enum UnaryOpCode {
    UNARY_POSITIVE,
    UNARY_NEGATIVE,
    UNARY_NOT
};

enum BinaryOpCode {
    NOTHING = 0,
    BINARY_ADD,
    BINARY_SUB,
    BINARY_MUL,
    BINARY_DIV,
    BINARY_MOD,
    BINARY_EQ,
    BINARY_NE,
    BINARY_LT,
    BINARY_LE,
    BINARY_GT,
    BINARY_GE,
    BINARY_LOGICAL_AND,
    BINARY_LOGICAL_OR
};

#endif //CODE_OPCODE_H
